version: '3.9'

services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - 80:80
            - 443:443
